# Generated by Django 4.1.7 on 2023-03-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='imagefield',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
